# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package files first for better Docker layer caching
COPY package.json package-lock.json ./

# Install dependencies
RUN npm ci --ignore-scripts

# Copy source code and config files
COPY src ./src
COPY tsconfig.json ./

# Build the project
RUN npm run build

# Set environment variables for Smithery
ENV NODE_ENV=production
ENV TRANSPORT=http
ENV PORT=8081
ENV HOST=0.0.0.0

# Expose port 8081 for Smithery HTTP transport
EXPOSE 8081

# Default command to start the MCP server
CMD ["node", "build/index.js"]
