name: Validate Package

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Perform npm publish with --dry-run flag'
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Pack
      run: npm pack
      
    - name: List package contents
      run: tar -tvf *.tgz
    
    - name: Validate package with dry-run
      if: ${{ github.event.inputs.dry_run == 'true' }}
      run: npm publish --dry-run
      
    - name: Upload package artifact
      uses: actions/upload-artifact@v4
      with:
        name: npm-package
        path: "*.tgz"
        retention-days: 7